version: 2.1
 version: 2
 jobs: # we now have TWO jobs, so that a workflow can coordinate them!
   
orbs:
  node: circleci/node@1.1.6
jobs:
  one: # This is our first job.
    docker: # it uses the docker executor
       - image: circleci/ubuntu:18.04 # specifically, a docker image with ruby 2.4.1
     # Steps are a list of commands to run inside the docker container above.
     steps:
       - checkout # this pulls pulls code down from GitHub
       - run: echo "A first hello" # This prints "A first hello" to stdout.
       - run: npm install
  two: # This is our second job.
     docker: # it runs inside a docker image, the same as above.
       - image: circleci/ubuntu:18.04
workflows:
    one_and_two: # this is the name of our workflow
     jobs: # and here we list the jobs we are going to run.
       - one
       - two
