version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
   approve:
      - request-testing:
          type: approval
          requires:
            - build
      - deploy-aws:
          requires:
            - request-testing
   steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  deployCode:
    docker: # it runs inside a docker image, the same as above.
       - image: circleci/node:13.12
    
  build-and-test:
    docker: # it runs inside a docker image, the same as above.
       - image: circleci/node:13.12
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - approve
        - deployCode
        
        
